name: Valhalla Fitness Marketing
favicon: null
layout_spectrum: 0.12299
typography_spectrum: 0.51244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9e9b96'
    - '#6b696a'
    - '#403b41'
    - '#cfcdc1'
    - '#ecece4'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
